import React, { useEffect, useMemo, useRef, useState } from 'react'
import { createRoot } from 'react-dom/client'
import { BarChart3, ChevronDown, GripVertical, Minus, Plus, RefreshCw, Settings2, Trophy, UserPlus, Users, X } from 'lucide-react'
import './styles.css'

// Lightweight i18n: English is the source language, German is selected for German browsers.
const locale = (navigator.language || 'en').toLowerCase().startsWith('de') ? 'de' : 'en'
const i18n = { en: { tournament:'TOURNAMENT', local:'Saved locally', players:'Players', table:'Table', rounds:'Rounds', add:'Add player', participants:'PARTICIPANTS', ranking:'RANKING', schedule:'SCHEDULE', create:'Create round', all:'All players', registered:'registered', ready:'Ready for the first serve?', intro:'Add all participants to start your tournament.', noRounds:'No rounds yet', firstRound:'Create the first round when all players are ready.', wins:'WINS', losses:'LOSSES', points:'POINTS', difference:'POINT DIFFERENCE', position:'POS.', sorted:'Sorted by wins', note:'Points = wins × 2 · Point difference = points scored − opponent points', addTitle:'Add players', onePerLine:'One name per line', cancel:'Cancel', addButton:'Add', oddTitle:'Odd number of players', oddQuestion:'Who should receive the automatic win?', automatic:'Automatically by standings', choose:'Choose a player', bye:'Bye', match:'matches', round:'ROUND' }, de: { tournament:'TURNIER', local:'Lokal gespeichert', players:'Spieler', table:'Tabelle', rounds:'Runden', add:'Spieler hinzufügen', participants:'TEILNEHMER', ranking:'RANGLISTE', schedule:'SPIELPLAN', create:'Runde erstellen', all:'Alle Spieler', registered:'registriert', ready:'Bereit für den ersten Aufschlag?', intro:'Füge alle Teilnehmenden hinzu, um dein Turnier zu starten.', noRounds:'Noch keine Runden', firstRound:'Erstelle die erste Runde, sobald alle Spieler bereit sind.', wins:'SIEGE', losses:'NIEDERLAGEN', points:'PUNKTE', difference:'PUNKTE-DIFFERENZ', position:'POS.', sorted:'Nach Siegen sortiert', note:'Punkte = Siege × 2 · Punktedifferenz = erzielte Punkte − gegnerische Punkte', addTitle:'Spieler hinzufügen', onePerLine:'Ein Name pro Zeile', cancel:'Abbrechen', addButton:'Hinzufügen', oddTitle:'Ungerade Spielerzahl', oddQuestion:'Wer erhält den automatischen Sieg?', automatic:'Automatisch nach Tabellenplatz', choose:'Spieler auswählen', bye:'Bye', match:'Begegnungen', round:'RUNDE' } }
const t = key => i18n[locale][key]
document.documentElement.lang = locale

const seed = [
  { id: '1', name: 'Mia Schneider', wins: 2, losses: 0, scored: 42, conceded: 29 },
  { id: '2', name: 'Noah Weber', wins: 2, losses: 1, scored: 54, conceded: 48 },
  { id: '3', name: 'Lina Müller', wins: 1, losses: 1, scored: 39, conceded: 40 },
  { id: '4', name: 'Elias Keller', wins: 1, losses: 1, scored: 45, conceded: 43 },
  { id: '5', name: 'Lea Fischer', wins: 1, losses: 2, scored: 51, conceded: 56 },
  { id: '6', name: 'Jonas Baumann', wins: 0, losses: 2, scored: 31, conceded: 46 },
]
const uid = () => Math.random().toString(36).slice(2, 9)

function Dialog({ dialogRef, children }) { return <dialog ref={dialogRef} className="dialog">{children}</dialog> }
function App() {
  const [players, setPlayers] = useState(() => JSON.parse(localStorage.getItem('players') || 'null') || seed)
  const [rounds, setRounds] = useState(() => JSON.parse(localStorage.getItem('rounds') || 'null') || [])
  const [page, setPage] = useState(t('players'))
  const [sort, setSort] = useState('wins'); const [desc, setDesc] = useState(true)
  const [draft, setDraft] = useState(''); const [dragged, setDragged] = useState(null)
  const bulkRef = useRef(); const byeRef = useRef(); const [byeMode, setByeMode] = useState('auto')
  useEffect(() => localStorage.setItem('players', JSON.stringify(players)), [players])
  useEffect(() => localStorage.setItem('rounds', JSON.stringify(rounds)), [rounds])
  const stats = useMemo(() => players.map(p => ({ ...p, diff: p.scored - p.conceded, points: p.wins * 2 })), [players])
  const sorted = useMemo(() => [...stats].sort((a,b) => { let x = sort === 'name' ? a.name.localeCompare(b.name) : a[sort]-b[sort]; return (desc ? -1 : 1) * (x || a.name.localeCompare(b.name)) }), [stats, sort, desc])
  const toggleSort = key => { if (sort === key) setDesc(!desc); else { setSort(key); setDesc(key !== 'name') } }
  const addBulk = () => { const names = draft.split('\n').map(n => n.trim()).filter(Boolean); setPlayers([...players, ...names.map(name => ({ id: uid(), name, wins: 0, losses: 0, scored: 0, conceded: 0 }))]); setDraft(''); bulkRef.current.close() }
  const deletePlayer = id => setPlayers(players.filter(p => p.id !== id))
  const makeRound = () => { if (players.length < 2) return; if (players.length % 2) byeRef.current.showModal(); else createRound(null) }
  const createRound = byeId => { const available = players.filter(p => p.id !== byeId).sort((a,b) => b.wins-a.wins || (b.scored-b.conceded)-(a.scored-a.conceded)); const matches = []; for (let i=0;i<available.length;i+=2) matches.push({ id: uid(), a: available[i].id, b: available[i+1].id, scoreA:'', scoreB:'' }); setRounds([...rounds, { number: rounds.length+1, bye: byeId, matches }]); byeRef.current?.close() }
  const updateRound = (ri, matches) => setRounds(rounds.map((r,i) => i===ri ? {...r,matches} : r))
  const name = id => players.find(p => p.id === id)?.name || 'Unbekannt'
  const nav = [{ label:t('players'), icon:Users }, { label:t('table'), icon:BarChart3 }, { label:t('rounds'), icon:Trophy }]
  return <div className="app-shell">
    <header><div className="brand"><div className="brand-mark"><Trophy size={20}/></div><div><div className="brand-title">Courtly</div><div className="brand-sub">BADMINTON TURNIER</div></div></div><div className="header-actions"><span className="live"><i/> Lokal gespeichert</span><button className="icon-btn"><Settings2 size={18}/></button></div></header>
    <main><aside><div className="side-label">TURNIER</div>{nav.map(({label,icon:Icon})=><button key={label} className={`nav-item ${page===label?'active':''}`} onClick={()=>setPage(label)}><Icon size={18}/>{label}{label==='Runden'&&rounds.length>0&&<span className="nav-badge">{rounds.length}</span>}</button>)}<div className="side-card"><div className="side-card-icon"><Users size={17}/></div><div><b>{players.length} Spieler</b><small>{rounds.length} {rounds.length===1?'Runde':'Runden'}</small></div></div></aside>
    <section className="content">{page==='Spieler'&&<Players players={players} deletePlayer={deletePlayer} onAdd={()=>bulkRef.current.showModal()}/>} {page==='Tabelle'&&<Table sorted={sorted} toggleSort={toggleSort} desc={desc}/>} {page==='Runden'&&<Rounds rounds={rounds} players={players} name={name} makeRound={makeRound} dragged={dragged} setDragged={setDragged} updateRound={updateRound}/>}</section></main>
    <Dialog dialogRef={bulkRef}><div className="dialog-head"><div><h2>Spieler hinzufügen</h2><p>Ein Name pro Zeile</p></div><button className="icon-btn" onClick={()=>bulkRef.current.close()}><X size={18}/></button></div><textarea autoFocus value={draft} onChange={e=>setDraft(e.target.value)} placeholder={'Anna Meier\nLukas Huber\n...'} /><div className="dialog-actions"><button className="button ghost" onClick={()=>bulkRef.current.close()}>Abbrechen</button><button className="button primary" onClick={addBulk}><UserPlus size={16}/> Hinzufügen</button></div></Dialog>
    <Dialog dialogRef={byeRef}><div className="dialog-head"><div><h2>Ungerade Spielerzahl</h2><p>Wer erhält den automatischen Sieg?</p></div><button className="icon-btn" onClick={()=>byeRef.current.close()}><X size={18}/></button></div><label className="radio"><input type="radio" checked={byeMode==='auto'} onChange={()=>setByeMode('auto')}/> Automatisch nach Tabellenplatz</label><label className="radio"><input type="radio" checked={byeMode!=='auto'} onChange={()=>setByeMode(players[0]?.id)}/> Spieler auswählen</label>{byeMode!=='auto'&&<select value={byeMode} onChange={e=>setByeMode(e.target.value)}>{players.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select>}<div className="dialog-actions"><button className="button ghost" onClick={()=>byeRef.current.close()}>Abbrechen</button><button className="button primary" onClick={()=>createRound(byeMode==='auto' ? [...players].sort((a,b)=>a.wins-b.wins)[0].id : byeMode)}>Runde erstellen</button></div></Dialog>
  </div>
}
function PageTitle({eyebrow,title,children}) { return <div className="page-title"><div><div className="eyebrow">{eyebrow}</div><h1>{title}</h1></div>{children}</div> }
function Players({players,deletePlayer,onAdd}) { return <><PageTitle eyebrow="TEILNEHMER" title="Spieler"><button className="button primary" onClick={onAdd}><Plus size={17}/> Spieler hinzufügen</button></PageTitle><div className="hero-card"><div className="hero-icon"><Users size={22}/></div><div><b>Bereit für den ersten Aufschlag?</b><p>Füge alle Teilnehmenden hinzu, um dein Turnier zu starten.</p></div><span className="count-pill">{players.length} Spieler</span></div><div className="section-head"><h2>Alle Spieler</h2><span>{players.length} registriert</span></div><div className="player-grid">{players.map((p,i)=><article className="player-card" key={p.id}><span className="avatar">{p.name.split(' ').map(x=>x[0]).join('').slice(0,2)}</span><div className="player-info"><b>{p.name}</b><small>#{String(i+1).padStart(2,'0')} · {p.wins} Siege</small></div><button className="delete-btn" onClick={()=>deletePlayer(p.id)} title="Löschen"><X size={16}/></button></article>)}</div></> }
function Table({sorted,toggleSort,desc}) { const cols=[['name','NAME'],['wins','SIEGE'],['losses','NIEDERLAGEN'],['points','PUNKTE'],['diff','PUNKTE-DIFFERENZ']]; return <><PageTitle eyebrow="RANGLISTE" title="Tabelle"><span className="round-status"><i/> Nach Siegen sortiert</span></PageTitle><div className="table-wrap"><table><thead><tr><th>POS.</th>{cols.map(([key,label])=><th key={key}><button onClick={()=>toggleSort(key)}>{label}<ChevronDown size={14} className={desc?'sort-down':''}/></button></th>)}</tr></thead><tbody>{sorted.map((p,i)=><tr key={p.id}><td><span className={`rank rank-${i+1}`}>{i+1}</span></td><td><b>{p.name}</b></td><td>{p.wins}</td><td>{p.losses}</td><td><strong>{p.points}</strong></td><td className={p.diff>=0?'positive':'negative'}>{p.diff>0?'+':''}{p.diff}</td></tr>)}</tbody></table></div><p className="table-note">Punkte = Siege × 2 · Punktedifferenz = erzielte Punkte − gegnerische Punkte</p></> }
function Rounds({rounds,players,name,makeRound,dragged,setDragged,updateRound}) { return <><PageTitle eyebrow="SPIELPLAN" title="Runden"><button className="button primary" onClick={makeRound}><RefreshCw size={16}/> Runde erstellen</button></PageTitle>{rounds.length===0?<div className="empty"><Trophy size={30}/><h2>Noch keine Runden</h2><p>Erstelle die erste Runde, sobald alle Spieler bereit sind.</p></div>:<div className="round-list">{rounds.map((r,ri)=><div className="round-card" key={r.number}><div className="round-head"><div><span className="round-kicker">RUNDE {String(r.number).padStart(2,'0')}</span><h2>{r.matches.length} Begegnungen</h2></div>{r.bye&&<span className="bye-pill">Bye: {name(r.bye)}</span>}</div><div className="matches">{r.matches.map((m,mi)=><div className="match" key={m.id} onDragOver={e=>e.preventDefault()} onDrop={()=>{if(dragged){const next=r.matches.map((x,j)=>j===mi?{...x,a:dragged}:x); updateRound(ri,next);setDragged(null)}}}><span className="match-no">{String(mi+1).padStart(2,'0')}</span><span className="drag-hint" draggable onDragStart={()=>setDragged(m.a)}><GripVertical size={16}/>{name(m.a)}</span><span className="versus">VS</span><span className="drag-hint" draggable onDragStart={()=>setDragged(m.b)}><GripVertical size={16}/>{name(m.b)}</span><div className="score"><input value={m.scoreA} onChange={e=>updateRound(ri,r.matches.map((x,j)=>j===mi?{...x,scoreA:e.target.value}:x))}/><b>:</b><input value={m.scoreB} onChange={e=>updateRound(ri,r.matches.map((x,j)=>j===mi?{...x,scoreB:e.target.value}:x))}/></div></div>)}</div></div>)}</div>}</> }
createRoot(document.getElementById('root')).render(<App />)
